routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home@main');
Route::post('login', 'User@login')->name('login');
Route::get('login', 'Home@main')->name('login');
Route::get('forgot-password', 'User@forgotPassword')->name('user.forgot-password');
Route::post('forgot-password', 'User@resetPassword')->name('user.reset-password');

Route::resource('user', 'User');
Route::group(['middleware' => 'auth'], function () {
    Route::get('change-password', 'User@changePassword')->name('change-password');
    Route::post('change-password', 'User@updatePassword')->name('change-password');
    Route::get('recharge', 'Recharge@request')->name("recharge");
    Route::get('digest', 'User@digest')->name('digest');
    Route::delete('logout', 'User@logout')->name('user.logout');
    Route::resource('key', 'Key');
    Route::resource('pdf', 'WebPdf');
    Route::get('logout', 'User@logout')->name('logout');
});
Route::get('user/create','User@create')->name("user.create");

resources/views/helpers/notifier.blade.php
@if(session('message'))
    <div class="row justify-content-center">
        <div class="card card-{{$type ?? session('type') ?? 'success'}} text-center z-depth-2 mb-1">
            <div class="card-block">
                <p class="white-text mb-0">{{session('message')}}</p>
            </div>
        </div>
    </div>
@endif

resources/views/helpers/sidebar.blade.php
<div id="sidebar-wrapper">
    <ul class="sidebar-nav ">
        <li class="sidebar-brand ">
            <a href="/" class="text-danger text-center">
                Administrator
            </a>
        </li>
        <li class="{{active(url('/'))}}">
            <a class="text-center  {{active(url('/'))}}" href="/">Dashboard</a>
        </li>
        <li class="{{active(route('key.index'))}}">
            <a class="text-center {{active(route('key.index'))}}" href="{{route('key.index')}}">Keys</a>
        </li>
        <li class="{{active(route('change-password'))}}">
            <a class="text-center {{active(route('change-password'))}}" href="{{route('change-password')}}">Change
                Password</a>
        </li>
        <li class="{{active(route('digest'))}}">
            <a class="text-center {{active(route('digest'))}}" href="{{route('digest')}}">How to digest ?</a>
        </li>
        <li class="small {{active(route('logout'))}}">
            <a class="text-center {{active(route('logout'))}}" href="{{route('logout')}}">Log Out</a>
        </li>
    </ul>
</div>