routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Home@main');
Route::post('login', 'User@login')->name('login');
Route::get('login', 'Home@main')->name('login');
Route::get('forgot-password', 'User@forgotPassword')->name('user.forgot-password');
Route::post('forgot-password', 'User@resetPassword')->name('user.reset-password');

Route::resource('user', 'User');
Route::group(['middleware' => 'auth'], function () {
    Route::get('change-password', 'User@changePassword')->name('change-password');
    Route::post('change-password', 'User@updatePassword')->name('change-password');
    Route::get('recharge', 'Recharge@request')->name("recharge");
    Route::get('digest', 'User@digest')->name('digest');
    Route::delete('logout', 'User@logout')->name('user.logout');
    Route::resource('key', 'Key');
    Route::resource('pdf', 'WebPdf');
    Route::get('logout', 'User@logout')->name('logout');
});
Route::get('user/create','User@create')->name("user.create");

app/Key.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Key extends Model
{
    public $fillable = ['key','domain'];

    public function pdfs(){
        return $this->hasMany(KeyPdf::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Key.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Key as KeyCreator;

class Key extends Controller
{

    public function create(){
        return view('key.create');
    }
    public function index(){
        return view('key.lists');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $message = 'Password was invalid';
        if(auth()->attempt(array_merge($request->only('password'),['username'=>auth()->user()->username]))){
            $request->user()->keys()->save(new KeyCreator(['key'=>str_random(15)]));
            $message = "Key has been successfully created.";
        }
        return redirect(route("key.index"))->with("message",$message);
    }

    /**
     * Display the specified resource.
     *
     * @param $key
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @internal param int $id
     */
    public function show($key)
    {
        return view('key.show')->with('pdfs',KeyCreator::where('key',$key)->first()->pdfs);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
       $request->user()->keys()->where('id',$id)->delete();
       return back()->with('message','Key has been successfully deleted');
    }
}

resources/views/key/core.blade.php
@extends('template')

resources/views/key/create.blade.php
@extends('key.core')

@section('content')
    <div class="row justify-content-center">
        <div class="col-lg-6 col-md-8">
            <form action="{{ route('key.store') }}" method="post">
                <div class="card">
                    <div class="card-block">
                        <div class="form-header  purple darken-4">
                            <h3><i class="fa fa-lock"></i> Create Key:</h3>
                        </div>
                        {{csrf_field()}}
                        <div class="md-form">
                            <i class="fa fa-lock prefix"></i>
                            <input class="form-control" type="password" name="password"
                                   required/>
                            <label for="form4">Password</label>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-deep-purple"> Log In</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/key/lists.blade.php
@extends('key.core')

@section('content')
    @if(auth()->user()->keys()->count() > 0)
       @include("key.table")
    @else
        <div class="col-sm-12">
            <div class="card card-success text-center z-depth-2 mb-1">
                <div class="card-block">
                    <p class="white-text mb-0">
            You have no keys. Please create one <a href="{{ route('key.create') }}">here</a>.
                    </p>
                </div>
            </div>
        </div>
    @endif

@endsection

resources/views/key/show.blade.php
@extends('key.core')

@section('content')
    @if($pdfs->count() > 0)
        <div class="row justify-content-center ">
          <div class="col-sm-10">
              <table class="table">
                  <thead class="thead-inverse">
                  <th>ID</th>
                  <th>Name</th>
                  <th>Created at</th>
                  <th>Actions</th>
                  </thead>
                  <tbody>
                  @foreach($pdfs as $pdf)
                      <tr>
                          <td>{{$pdf->id}}</td>
                          <td>{{$pdf->name}}</td>
                          <td title="{{$pdf->created_at}}">{{$pdf->created_at->toFormattedDateString()}}</td>
                          <td>
                              <a target="_blank" class="btn btn-info"
                                 href="{{route('pdf.show',$pdf)}}?type=print"><i class="fa fa-cloud-download"></i>
                                  <strong>View</strong></a>
                              <a class="btn btn-success" href="{{route('pdf.show',$pdf)}}?type=download"><i
                                          class="fa fa-cloud-download"></i>
                                  <strong>Download</strong></a>
                              <form class="d-inline-block" method="post"
                                    action="{{route('pdf.destroy',$pdf)}}">{{csrf_field()}}{{method_field('delete')}}
                                  <input type="hidden" value="{{$pdf->id}}">
                                  <button type="submit" class="btn btn-danger"> Delete</button>
                              </form>
                      </tr>
                  @endforeach
                  </tbody>
              </table>
          </div>
        </div>
    @else
        <div class="col-sm-12">
            <div class="card card-success text-center z-depth-2 mb-1">
                <div class="card-block">
                    <p class="white-text mb-0">
                        No PDF has been saved with this api key.
                    </p>
                </div>
            </div>
        </div>
    @endif
@endsection

resources/views/key/table.blade.php
<div class="container">
    <div style="margin: 0 auto;">
        <a href="{{route('key.create')}}" class="btn btn-blue-grey pull-right">Create</a>
        <table class="table table-striped">
            <thead class="thead-inverse">
            <th class="text-capitalize">key id</th>
            <th class="text-capitalize">key</th>
            <th class="text-capitalize">created at</th>
            <th class="text-capitalize">count of pdf</th>
            <th class="text-capitalize">actions</th>
            </thead>
            <tbody>
            @foreach(auth()->user()->keys()->withCount('pdfs')->get() as $key)
                <tr class="">
                    <td class="align-middle">{{ $key->id }}</td>
                    <td class="key-holder align-middle">{{ $key->key }}
                    </td>
                    <td class="align-middle" title="{{ $key->created_at }}">{{ $key->created_at->toFormattedDateString() }}</td>
                    <td class="align-middle">{{$key->pdfs_count}}</td>
                    <td>
                        <a title="It will show you list of pdf created by this key (only cached)" href="{{ route('key.show',$key->key) }}" class="btn btn-info">View</a>
                        <form class="d-inline-block" action="{{ route('key.destroy',$key) }}"
                              method="POST">{{ csrf_field() }}{{ method_field('delete') }}
                            <button title="Be careful" class="btn btn-danger button" type="submit">
                                <strong>Destroy</strong></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>